### ISSUE TITLE
frus1969-76ve16

### ISSUE THREAD

**Issue by machalou** [joewiz/frus-tei#102]
- [x] Passes FRUS TEI Schematron check
- [x] Passes RelaxNG schema check
- [ ] Scripts run
- [x] Commit schema-compliant file to SVN
- [x] Upload the FRUS TEI file into localhost
- [x] Upload page images to S3
- [x] Typography and characters
- [x] Source note coding
- [x] Table of contents
- [ ] Tables, both participant and other
- [ ] Openers and assorted segs
- [x] Front matter
- [x] Back matter
- [x] Random sample
- [x] Volume metadata
- [x] Ebook generation and review

**Comment by machalou** [comment]
Changed all examples of gap/@extent to gap@quantity
Uploaded partial image files -- need to email Cherie with missing images
Changed preface signature coding

**Comment by seckroth** [comment]
random doc check
-d#100-105
-d#149-154
-d#52 changed tagging of SRG from NARA Record Group to Senior Review Group throughout file
-d#52-54, 59, 61
-d#63 fixed incorrect xref
-d#71-73
d#11-18
