### ISSUE TITLE
Review FRUS 69-76 vol E15p2

### ISSUE THREAD

**Issue by tomfaith** [joewiz/frus-tei#11]
- [x] Passes FRUS TEI Schematron check
- [x] Passes RelaxNG schema check
- [x] Commit schema-compliant file to SVN
- [x] Upload the FRUS TEI file into localhost
- [ ] Upload page images to S3
- [x] Table of contents
- [x] Front matter
- [x] Back matter
- [x] Random sample
- [x] Volume metadata

**Comment by joewiz** [comment]
This issue was moved to HistoryAtState/frus#15
