### ISSUE TITLE
frus1969-76v21

### ISSUE THREAD

**Issue by machalou** [joewiz/frus-tei#18]
- [x] Passes FRUS TEI Schematron check
- [x] Passes RelaxNG schema check
- [x] Commit schema-compliant file to SVN
- [x] Upload the FRUS TEI file into localhost
- [x] Upload page images to S3
- [x] Typography and characters
- [x] Source note coding
- [x] Table of contents
- [x] Front matter
- [x] Back matter
- [x] Random sample
- [x] Volume metadata

**Comment by seckroth** [comment]
- fixed d#2,4, and 5. `persName` tags for Allende were empty
- added `@type='participants' and 'to` where missing in lists and changed `<list>` to `<p>` in docs that were not typeset at as a 16
- d#67, 105, 185, 293, 303, 307 need attributes/values for lists in intelligence info cables

**Comment by seckroth** [comment]
changes in pages 
- d#94, added missing "Source:" to source note
