### ISSUE TITLE
implement rendition handling for tables

### ISSUE THREAD

**Issue by joewiz** [joewiz/frus-tei#77]
Notes from @vak2ve commit messages

- revision 3992
    - frus1947v05: in tables where the text occupies more than one column width the cell content is automatically centered. Is it possible to change that default alignment to rendition="#left"? It would reflect the printed page more accurately and make including other rendition values possible. See for example TOC for Pentagon Talks at ch2 and participants list at d401 of this volume.
- revision 4004
    - frus1946v11: wide table at d64
- revision 4016
    - frus1946v10: participant tables are centered in this volume so it would be a perfect time to implement the table-wide rendition values we talked about. 
    - frus1946v10: wide table at d411-may need to insert image as in previous instances of wide tables

**Comment by joewiz** [comment]
Notes from @vak2ve email:

Implementing rendition values and CSS instructions on the table as well as cell level. Not all—in fact, very few—tables appear on the pages of the hard copy with the same width given to them automatically in digital form. The ability to align an entire table and specify the width of each column would go a long way to increasing fidelity to the printed page even more than we have already. New tags would be:

- `rendition=“#centerBlock”`, `rendition=“#unstyled"`
- `<html:colgroup>`, with the percentage width applied as an attribute. 

Examples from FO:

- http://founders.archives.gov/documents/Hamilton/01-13-02-0103
```
<table rows="9" cols="2" rend="width:100%;">
    <html:colgroup width="65%;"/>
    <html:colgroup width="15%;"/>
    <html:colgroup width="20%;"/>
    <row>
        <cell/>
        <cell/>
        <cell role="num">Dollars</cell>
    </row>
    <row>
        <cell>au lr. Decembre prochain</cell>
        <cell/>
        <cell role="num">64,935. ¹⁄₀₀</cell>
    </row>
</table>
```
- http://founders.archives.gov/documents/Hamilton/01-13-02-0033-0002

```
<table rendition="#unstyled" rend="width:100%;margin-top:2em;">
    <html:colgroup style="width:6%;"/>
    <html:colgroup style="width:11%;"/>
    <html:colgroup style="width:3%;"/>
    <html:colgroup style="width:15%;"/>
    <html:colgroup style="width:35%;"/>
    <html:colgroup style="width:10%;"/>
    <html:colgroup style="width:10%;"/>
    <html:colgroup style="width:10%;"/>
    <row>
        <cell cols="8" rendition="#center #all-caps #border-bottom-double">For the Support and
            Repairs of Light Houses, Beacons, Buoys and Public Piers.</cell>
    </row>
    <row>
        <cell/>
        <cell/>
        <cell role="num" rend="padding-right:0.3em;"/>
        <cell cols="3" rendition="#border-bottom" rend="padding-top:1em;">Benjamin Lincoln
            Superintendant of the Light houses in the State of Massachusetts.</cell>
        <cell/>
        <cell role="num"/>
    </row>
</table>
```

**Comment by joewiz** [comment]
@vak2ve Could you please choose a table we could use as the basis of a test, apply the <html:colgroup> to that table, and commit it (or if you've already done this, point me to it)?

**Comment by vak2ve** [comment]
Committed very simple test table at d616 of 1946v10, though an error message resulted when I applied html:colgroup that said "the prefix "html" for element html:colgroup is not bound."

**Comment by joewiz** [comment]
Okay, in revision 4019 I took a swipe at several of these issues:

> initial work on table styling improvements
> - added handling for the `@rendition` attribute on the table element 
> - added handling for `html:colgroup`
> - removed centered default text alignment for column-spanning cells; they should inherit the default CSS left alignment, but we should be able to override this with `@rendition` values.

For example, here's `http://localhost:8080/historicaldocuments/frus1946v10/d616`, showing that the table's `@rend="width: 80%"` and the `html:colgroup` widths have been preserved:

![screen shot 2015-07-16 at 2 08 04 pm](https://cloud.githubusercontent.com/assets/59118/8731663/e732527e-2bc6-11e5-96a3-b638e7162160.png)

I didn't explicitly address tables that exceeded the width of the page (e.g., revision 4004's wide table at frus1946v11/d64) or your ideas to replace certain tables with images.  

Could you see how the tables in question look, with the new rendition handling at your disposal?

**Comment by joewiz** [comment]
The latest commits completed these enhancements, as confirmed by @vak2ve - thanks for your recommendations!
